import { writeFileSync } from "fs";
import { resolve, basename } from "path";
import { parseRiveFile } from "../parser/riveParser.js";
import type { RiveFileMetadata } from "../parser/types.js";

function toConstantCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/([a-z])([A-Z])/g, "$1_$2")
    .toUpperCase()
    .replace(/^_+|_+$/g, "");
}

function generateFromMeta(meta: RiveFileMetadata, fileLabel: string): string {
  const lines: string[] = [];
  const prefix = toConstantCase(fileLabel);

  lines.push(`export const ${prefix}_ARTBOARDS = {`);
  for (const ab of meta.artboards) {
    lines.push(`  ${toConstantCase(ab.name)}: '${ab.name}',`);
  }
  lines.push(`} as const;`);
  lines.push("");
  lines.push(
    `export type ${prefix}ArtboardName = typeof ${prefix}_ARTBOARDS[keyof typeof ${prefix}_ARTBOARDS];`,
  );
  lines.push("");

  lines.push(`export const ${prefix}_STATE_MACHINES = {`);
  for (const ab of meta.artboards) {
    for (const sm of ab.stateMachines) {
      const smKey = toConstantCase(sm.name);
      lines.push(`  ${smKey}: {`);
      lines.push(`    name: '${sm.name}',`);
      if (sm.inputs.length > 0) {
        lines.push(`    inputs: {`);
        for (const input of sm.inputs) {
          lines.push(
            `      ${toConstantCase(input.name)}: { name: '${input.name}', type: '${input.type}' as const },`,
          );
        }
        lines.push(`    },`);
      } else {
        lines.push(`    inputs: {},`);
      }
      lines.push(`  },`);
    }
  }
  lines.push(`} as const;`);
  lines.push("");

  lines.push(`export const ${prefix}_ANIMATIONS = {`);
  for (const ab of meta.artboards) {
    for (const anim of ab.animations) {
      lines.push(
        `  ${toConstantCase(anim.name)}: { name: '${anim.name}', artboard: '${ab.name}', fps: ${anim.fps}, duration: ${anim.duration.toFixed(3)} },`,
      );
    }
  }
  lines.push(`} as const;`);

  return lines.join("\n");
}

export async function generateTypes(
  rivFilePath: string,
  outputPath?: string,
): Promise<string> {
  const absRiv = resolve(rivFilePath);
  const meta = await parseRiveFile(absRiv);

  const fileLabel = basename(absRiv, ".riv");
  const generated = generateFromMeta(meta, fileLabel);

  const header = [
    `/** Auto-generated by rive-mcp-analyzer */`,
    `/** Source: ${absRiv} */`,
    `/** Generated: ${new Date().toISOString()} */`,
    ``,
  ].join("\n");

  const output = header + generated;

  if (outputPath) {
    const absOutput = resolve(outputPath);
    writeFileSync(absOutput, output, "utf-8");
  }

  return output;
}
